spring:
  config:
    import:
      - application-db.yml
      - application-video.yml
  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          kakao:
            client-id: b55deedfb808699dabf0e043ab7ec5de
            client-secret: c69TURhgvHKnLtzrvGVeaA1XS8oB48Sg
            redirect-uri: /login/oauth2/code/kakao
            scope: profile_nickname, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
          google:
            client-id: 831236545250-pcc05tuiq2o87jpolrvtce1v09gjmq9i.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile
          naver:
            client-id: WduH_0zvRQwvM1pdpq2c
            client-secret: CqOp6k7gjh
            redirect-uri: "http://localhost:8080/login/oauth2/code/{registrationId}"
            scope: nickname,email
            client-name: Naver
            authorization-grant-type: authorization_code

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
        oauth2:
          client: debug

jwt:
  secretKey: ssafy
  access:
    expiration: 60000
    header: Authorization
  refresh:
    expiration: 60000
    header: Refresh-Token
#    naver:
#      rest-api-key:
#      secret-key:
#      redirect-uri: http://localhost:9000/naverlogin
#      grant_type: authorization_code
#
#    google:
#      rest-api-key:
#      secret-key:
#      redirect-uri: http://localhost:9000/googlelogin
#      grant_type: authorization_code